// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type GetRootRes struct {
	SomeArg   string      `json:"some_arg"`
	TypeRoots []*TypeRoot `json:"TypeRoots"`
}

type TypeCompA1 struct {
	Field1  int            `json:"Field1"`
	Field2  string         `json:"Field2"`
	TableA1 []*TypeTableA1 `json:"TableA1"`
}

type TypeCompA2 struct {
	Field3  int            `json:"Field3"`
	Field4  string         `json:"Field4"`
	TableA2 []*TypeTableA2 `json:"TableA2"`
}

type TypeGroupA struct {
	EventID   int         `json:"EventId"`
	TimeStamp *time.Time  `json:"TimeStamp"`
	CompA1    *TypeCompA1 `json:"CompA1"`
	CompA2    *TypeCompA2 `json:"CompA2"`
}

type TypeRoot struct {
	ID     string        `json:"Id"`
	FieldA string        `json:"FieldA"`
	GroupA []*TypeGroupA `json:"GroupA"`
}

type TypeTableA1 struct {
	City string    `json:"City"`
	Date time.Time `json:"Date"`
}

type TypeTableA2 struct {
	F1 string    `json:"F1"`
	F2 time.Time `json:"F2"`
}
